import { pageMetadata } from '@/lib/site-metadata';
import { publicAsset } from '@/lib/site-path';
import Link from '@/components/site-link';
import { ArrowRight, Check, CornerDownLeft, Play, Terminal, FileText } from 'lucide-react';
import { Header, Footer, TextLink } from '@/components/site';

export const metadata = pageMetadata('/');
export default function Home() {
  return <><Header/><main id="main" tabIndex={-1}>
    <section className="hero wrap">
      <div className="hero-copy"><p className="eyebrow"><span/> PARTIAL-STANDARDS / IAP</p><h1>目的をそろえる。<br/>ずれを確かめる。<br/><em>協働を続ける。</em></h1><p className="hero-intro">IAPは、目的・完成条件・確認のしかたを共有するための仕様草案です。中核機能を実装したCodex連携の試験版を公開しています。実利用での負担軽減は、これから確かめます。</p><div className="actions"><Link className="button primary" href="/guide/developer#before">ひとりで架空例を試す <ArrowRight size={18}/></Link><a className="button quiet" href="#demo"><Play size={16}/> 99秒のデモを見る</a></div><p className="small-note">現在のお試しは、ターミナルでコマンドを実行できる方へ。macOS/LinuxとNode.js 22.13以降を使います。PMの参加やCodexへのログインは不要です。</p></div>
      <div className="workflow-board" role="group" aria-labelledby="workflow-title"><div className="board-heading"><h2 id="workflow-title">実装例：開発者・PM・Codexの協働</h2><span className="mono">01 → 04</span></div><div className="flow-item"><span className="step-dot">01</span><div><span className="role-tag pm">PM</span><h3>目的と完成条件を伝える</h3><p>「何ができれば完成か」をそろえる。</p></div></div><div className="developer-loop"><div className="loop-label"><span>開発者 ＋ Codex</span><span><CornerDownLeft size={16}/> 範囲内で繰り返す</span></div><div className="flow-item"><span className="step-dot">02</span><div><h3>途中成果を、目的と照合</h3><p>ずれの根拠と、次の一手を確かめる。</p></div></div><div className="flow-item"><span className="step-dot">03</span><div><h3>修正して、もう一度確認</h3><p>実装・テスト・再照合まで進める。</p></div></div></div><div className="flow-item"><span className="step-dot">04</span><div><span className="role-tag pm">PM・外部の関係者へ</span><h3>要点をまとめて共有する</h3><p>進捗・残り・次の一手・確認事項。</p></div></div><div className="board-foot"><Check size={16}/> 通常の修正は、毎回のPM承認待ちにしない。</div></div>
    </section>
    <section className="principle"><div className="wrap principle-inner"><p>進捗を共有することと、<br/><strong>作業を止めて判断を待つことは別。</strong></p><div>合意した範囲の修正は開発者側で進めます。<br/>目的・完成条件・範囲を変える必要があるときに、<br className="desktop-break"/>PMへの判断事項を切り出します。</div></div></section>
    <section className="section wrap" id="proposal"><div className="section-top"><div><p className="eyebrow">THE PROPOSAL</p><h2>協働の条件を、持ち運べる形に。</h2></div></div><div className="example-grid"><div><p>何を目指しているか。何ができれば完成か。いつ、どのように確かめるか。途中で止まったら、どこから戻るか。</p><p>人と人、人とAIの間にあるこうした条件を、文章と記録で扱うための提案がIAPです。</p></div><div><p>まずは小さな開発案件から。開発者が自分で作業を進めながら、PMとは短い共有でつながる流れを試しています。</p><TextLink href="/proposal">考え方・仕様草案を読む</TextLink></div></div></section><section className="section wrap" id="guide"><div className="section-top"><div><p className="eyebrow">START HERE</p><h2>実装例を、それぞれの立場から。</h2></div><p>IAP × Codexでは、PMと開発者を別々の人として扱います。</p></div><div className="guide-grid"><article className="guide-card"><Terminal size={26}/><span className="guide-index mono">GUIDE 01</span><h3>開発者の方へ</h3><p>案件フォルダーに導入し、Codexの作業中に照合を組み込みます。設定から共有までを順に確認できます。</p><TextLink href="/guide/developer">導入・作業のガイド</TextLink></article><article className="guide-card"><FileText size={26}/><span className="guide-index mono">GUIDE 02</span><h3>PM・依頼する方へ</h3><p>専用ツールのインストールは不要です。依頼で伝えること、届いた共有文の読み方、判断の返し方をまとめました。</p><TextLink href="/guide/pm">依頼・確認のガイド</TextLink></article></div></section>
    <section className="section wrap" id="flow"><div className="section-top"><div><p className="eyebrow">HOW IT WORKS</p><h2>修正に戻る。その根拠を残す。</h2></div></div><div className="example-grid"><div><span className="role-tag">架空のCSV検証案件</span><h3>依頼は、正常入力と<br/>不正入力の結果を確かめること。</h3><p>途中でログイン機能の設計へ広がったら、依頼の目的と成果を照合。完成条件を弱めずに、元の検証へ戻します。</p><p>未完成であること自体は、通常の作業途中です。範囲内で直せるものは、そのまま進めます。</p></div><div className="evidence-card"><div className="evidence-line"><span>完成条件</span><b>正常入力の合計 ／ 不正な行のエラー</b></div><div className="evidence-line"><span>観測した成果</span><b>ログイン画面を設計。CSVは未実行。</b></div><div className="evidence-result"><span className="status-dot"/>対象外へ進んでいる。条件は未達。</div><div className="next-step"><span>次の一手</span><strong>CSVの2つの入力を実行し、<br/>結果を報告へ。</strong><ArrowRight size={24}/></div><p className="caption">説明用の例。成果と根拠を読むのは、作業中のCodexです。</p></div></div></section>
    <section className="demo-section" id="demo"><div className="wrap"><div className="section-top"><div><p className="eyebrow">SEE THE FLOW</p><h2>役割と使い方を、99秒で。</h2></div><p>日本語字幕・BGM付き（読み上げなし）</p></div><video controls preload="metadata" playsInline aria-label="PMと開発者を分けたIAPの説明デモ"><source src={publicAsset("/media/iap-demo.mp4?v=20260924-bgm")} type="video/mp4"/><track kind="captions" src={publicAsset("/media/iap-demo.vtt?v=20260924-bgm")} srcLang="ja" label="日本語"/>お使いのブラウザは動画に対応していません。<Link href="/media/iap-demo.mp4?v=20260924-bgm" prefetch={false}>デモ動画を開く</Link></video><p className="caption">字幕は映像内に表示しています。プレーヤーから追加の字幕も選べます。<a href={publicAsset("/media/iap-demo.vtt?v=20260924-bgm")} download>字幕テキストを保存</a></p><p className="caption">検証結果をもとにした説明用の再構成です。専用アプリ画面や実案件の共同作業を録画したものではありません。</p><p className="caption">BGM：<a href="https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1600022">「Inspired」Kevin MacLeod（incompetech.com）</a> · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a><br/>冒頭99秒を使用し、音量調整・フェード・AAC変換・映像との同期を行っています。</p></div></section>
    <section className="section wrap closing"><div><p className="eyebrow">CURRENT STATE</p><h2>試して、確かめて、<br/>提案を育てる。</h2></div><div><p>完成条件との照合、修正・再確認、共有文生成、休止・復帰を実装しています。配布物の自動テストと実Codexの検証は、対象の版と範囲が異なります。他の人の導入や実利用の効果とあわせて、確認できたことを記録します。</p><TextLink href="/status">実装済みの範囲と、これから</TextLink></div></section>
  </main><Footer/></>;
}
