import { pageMetadata } from '@/lib/site-metadata';
import { publicAsset } from '@/lib/site-path';
import { DemoPlayer } from '@/components/demo-player';
import { RecoveryWalkthrough } from '@/components/recovery-walkthrough';
import { CodeBlock } from '@/components/code-block';
import Link from '@/components/site-link';
import { ArrowRight, Check, FileText, Hash, Terminal } from 'lucide-react';
import { Header, Footer, TextLink } from '@/components/site';
import evidence from '../public/cases/slack-recovery/evidence.json';

export const metadata = pageMetadata('/');
export default function Home() {
  return <><Header/><main id="main" tabIndex={-1}>
    <section className="hero recovery-hero wrap">
      <div className="hero-copy"><p className="eyebrow"><span/> IAP / 作業中の支援を、外へ。</p><h1>自分では気づけない<br/>脱線から、<br/><em>仕事へ戻れるように。</em></h1><p className="hero-intro">作業に入り込むと、本来の目的から外れても自力では気づけず、戻れない。IAPは、その検出と軌道修正を<strong>AIや周囲の仕組みに担わせる</strong>ための仕様草案です。</p><p className="hero-purpose">発達障害のある人が、自己監視を一人で背負わずに働けることを出発点にしています。</p><div className="actions"><a className="button primary" href="#recovery">Slackから始まる具体例を見る <ArrowRight size={18}/></a><Link className="button quiet" href="/proposal">考え方を読む</Link></div><p className="small-note">現在はCodex連携の試験版。Slackへの共有は本人が確認して貼り付けます。</p></div>
      <div className="recovery-preview"><div className="preview-heading"><span><Hash size={17}/> CSV集計の修正</span><span>利用場面の再現</span></div><div className="preview-request"><span className="case-label">依頼者 → 本人</span><p>「不正な金額があれば、<br/><strong>合計を出さずに止めてほしい。</strong>」</p></div><div className="preview-drift"><span>本人の作業が、それていく</span><p>「先にログイン画面を作り込もう」</p></div><div className="preview-intervention"><span className="case-label">AI・IAP → 本人</span><h2>その設計はいったん止めて、<br/>CSVのエラー修正へ。</h2><p>合意した目的と実行結果を照合。<br/>戻る作業を、具体的に示します。</p></div><div className="preview-result"><Check size={17}/><span>修正・再確認 → 結果をSlackで共有</span></div></div>
    </section>
    <section className="recovery-principle"><div className="wrap"><p>「気づいたら相談して」では、<br/><strong>気づけない局面を支えられない。</strong></p><div>確認のきっかけを外に置く。<br/>合意した目的に照らして、ずれを指摘する。<br/>そして、戻るための一手まで示す。</div></div></section>
    <section className="section wrap" id="recovery"><div className="section-top"><div><p className="eyebrow">ONE JOB, FROM REQUEST TO RECOVERY</p><h2>依頼から、脱線、復帰、報告まで。</h2></div><p>CSVの金額エラーを直す、ひとつの仕事。<br/>場面を進めると、誰が何をするかが分かります。</p></div><p className="case-disclosure"><strong>会話・本人の作業メモは再現例。</strong> テスト結果とIAPの出力は、架空案件で実際にCLIを実行した記録です。</p><RecoveryWalkthrough/></section>
    <section className="section wrap" id="evidence"><div className="section-top"><div><p className="eyebrow">WHAT ACTUALLY CHANGED</p><h2>戻った先で、エラーが直ったか。</h2></div><p>同じ入力で、修正前と修正後を確認しました。</p></div><div className="case-comparison"><article><span className="case-tag warn">修正前</span><h3>不正な値を、0円として通す。</h3><code>100 / abc / 300 → 合計400円</code><p>正常入力は通る。でも不正入力で止まらず、<br/>完成条件は<strong>1 / 2</strong>のまま。</p></article><article><span className="case-tag good">修正後</span><h3>不正な行で止め、合計を出さない。</h3><code>100 / abc / 300 → データ2行目のエラー</code><p>正常入力は600円、不正入力はエラー。<br/>再照合で完成条件<strong>2 / 2</strong>を確認。</p></article></div><details className="case-evidence-details"><summary>実際のIAP共有文と検証データを見る</summary><p>修正後に生成した共有文です。条件達成の評価と、依頼者による受け入れ判断を分けて表示します。</p><CodeBlock label="修正後のIAP共有文">{evidence.afterShare}</CodeBlock><div className="evidence-links"><a href={publicAsset('/cases/slack-recovery/evidence.json')}>全検証データ（JSON）</a><a href={publicAsset('/cases/slack-recovery/before-share.md')}>修正前の共有文</a><a href={publicAsset('/cases/slack-recovery/stale-share.md')}>変更直後の未評価表示</a><a href="https://github.com/aidhidesupport/iap/tree/main/examples/slack-recovery">再現用スクリプト</a></div><p className="caption">2026年9月28日／IAP 0.2.6／Node.js {evidence.nodeVersion}。非負整数の金額1列を扱う小さな検証例です。評価はこの例の根拠を読んで作成し、IAPで引用・条件・版の対応を確認しました。Slackへの送信、独立した利用者の行動変化、負担軽減は測定していません。</p></details></section>
    <section className="implementation-section" id="implementation"><div className="wrap"><div className="section-top"><div><p className="eyebrow">PURPOSE & CURRENT IMPLEMENTATION</p><h2>目指す支援と、いま動く範囲。</h2></div></div><div className="implementation-grid"><article><span className="case-label">目指していること</span><h3>本人が戻れないとき、外から介入する。</h3><p>本人が合意した目的を基準に、AIや周囲が脱線を検出し、軌道修正を働きかける。正当な目的変更と、その場の脱線を区別できる仕組みを目指します。</p></article><article><span className="case-label">試験版で動くこと</span><h3>成果の照合と、次の一手の記録。</h3><p>Codexの作業イベントで照合を促し、根拠付き評価・古い評価の失効・共有文生成を扱います。このページの例ではCLIを直接呼び出して検証しました。</p></article><article><span className="case-label">これから詰めること</span><h3>脱線を続けようとしたときの介入。</h3><p>誰が、どの合意に基づき、どこまで止めるかは未完成です。Slackの自動連携、本人が実際に復帰できるか、負担が減るかも今後の検証対象です。</p></article></div><p className="implementation-note">「ずれを表示できる」と「本人が仕事へ戻れる」は、別々に確かめます。</p></div></section>
    <section className="section wrap" id="guide"><div className="section-top"><div><p className="eyebrow">TRY THE CURRENT VERSION</p><h2>自分の立場から、試してみる。</h2></div></div><div className="guide-grid"><article className="guide-card"><Terminal size={26}/><span className="guide-index mono">開発者・支援の仕組みを作る方</span><h3>まず、手元の架空例から。</h3><p>成果の観測、古い評価の失効、共有文を確認します。macOS/Linux・Node.js 22.13以降・ターミナルを使用。最初の例にPMの参加やCodexログインは不要です。</p><TextLink href="/guide/developer#before">ひとりで試す手順</TextLink></article><article className="guide-card"><FileText size={26}/><span className="guide-index mono">依頼者・一緒に働く方</span><h3>戻る先を、一緒に決める。</h3><p>目的・完成条件・対象外を伝え、届いた共有文と成果を確かめる。本人だけに説明と調整を集めないための、依頼の書き方をまとめました。</p><TextLink href="/guide/pm">依頼・確認のガイド</TextLink></article></div><div className="case-feedback"><div><h3>この場面なら使えそう、ここでは戻れなさそう。</h3><p>使いたい場面や、試して止まった箇所を教えてください。</p></div><a className="button primary" href="https://github.com/aidhidesupport/iap/issues/new?template=feedback.md">フィードバックを送る <ArrowRight size={17}/></a></div></section>
    <section className="demo-section" id="demo"><div className="wrap"><div className="section-top"><div><p className="eyebrow">BACKGROUND</p><h2>IAPの理念と、協働の全体像。</h2></div><p>2分12秒の図解動画／BGM・画面内の説明付き</p></div><DemoPlayer/><p className="caption">仕様の考え方と開発での実装例を説明した既存動画です。上のCSVエラー修正を録画したものではありません。<a href={publicAsset('/media/iap-demo.vtt?v=20260924-diagram')} download>字幕テキストを保存</a></p><p className="caption">BGM：<a href="https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1600022">「Inspired」Kevin MacLeod（incompetech.com）</a> · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>。冒頭132秒を使用し、音量調整・フェード・AAC変換・映像との同期を行っています。</p></div></section>
  </main><Footer/></>;
}
