import { pageMetadata } from '@/lib/site-metadata';
import { Guide, Section, DataTable } from '@/components/guide';
import { TextLink } from '@/components/site';
export const metadata = pageMetadata('/proposal/');
export default function Proposal(){return <Guide title="協働の条件を、持ち運べる形に。" label="PROPOSAL" lead="IAP（Interaction Accommodation Protocol）は、対話や協働の条件を明確にし、本人の意思を保ちながら、人・AI・サービスの間で扱うための仕様草案です。" sections={ [['why','何を提案するか'],['record','記録すること'],['example','最初の実装例'],['process','提案を育てる流れ'],['read','仕様・フィードバック']] }>
<Section id="why" title="01 — 個人の気づきに、すべてを委ねない"><p>依頼の目的を取り違える。確認するタイミングを逃す。中断後に、どこから再開すればよいか分からなくなる。こうした協働の難しさに対して、条件・観測・確認・復帰の手順を、仕事の仕組みの中に置くことを提案します。</p><p>出発点は、発達特性のある人が協働で直面する困りごとです。診断の開示やIQを利用条件にせず、本人が必要な条件を選べることを重視しています。</p><div className="callout"><p><strong>partial-standardsの活動として提案する。</strong><br/>草案と具体例を出し、小さく試し、使えないところも記録する。その結果から、仕様を修正していきます。</p></div></Section>
<Section id="record" title="02 — 協働の前提を、記録にする"><DataTable headings={['扱うこと','具体例']} rows={ [['目的と完成条件','誰の何を解決し、どの成果を確認すれば完成と言えるか。'],['対象外と権限','今回は何をしないか。何を読めて、どの変更は判断が必要か。'],['確認と根拠','成果をいつ確かめるか。何を根拠に、達成・未達・未確認とするか。'],['中断と復帰','中断を選べること。再開するときの次の一手を残すこと。'],['変更と版','条件を変えたとき、以前の回答や評価を新しい成果に流用しないこと。']]}/><p>IAPは、現在のMCPの公式拡張や、採用済みの標準ではありません。異なる実装の間で条件を受け渡す仕組みは、今後の検討対象です。</p></Section>
<Section id="example" title="03 — 最初は、小さな開発案件から"><p>最初の適用例は、文章で依頼を受け、成果物を返す開発案件です。PMが目的・完成条件を伝え、開発者はCodexと成果を照合し、合意した範囲内で修正・確認を進めます。</p><p>範囲内の修正を毎回PMの承認待ちにせず、進捗は短い要約で共有します。目的・完成条件・範囲の変更に必要な判断は、PMへ切り出します。</p><p>Codex連携はIAPの一つの実装例です。ブラウザで条件を手入力する先行試作もありますが、両者のデータは同期していません。</p><TextLink href="/#demo">IAPの理念と実装例を見る（2分12秒）</TextLink></Section>
<Section id="process" title="04 — 提案 → 試行 → 記録 → 改善"><ol><li><strong>草案と実装例を読めるようにする。</strong>目的、使い方、未実装の範囲を明確にします。</li><li><strong>別々のPMと開発者で、一案件を試す。</strong>初回は30〜60分で途中成果を確認できる規模に絞ります。</li><li><strong>両者の負担と失敗を記録する。</strong>誤警告、手戻り、共有時間、確認時間、次も使いたい理由を残します。</li><li><strong>仕様と実装を直す。</strong>必要な項目と、余計な負担になった項目を見直します。</li></ol><p>試行で得た意見や反証を、次の草案と実装へ戻していきます。</p></Section>
<Section id="read" title="05 — 仕様を読む・反証を寄せる"><p><a href="https://github.com/aidhidesupport/iap/blob/main/IAP_SPEC.md">統合仕様草案 0.2</a>に、設計原則、状態遷移、権限、確認・復帰、検証ケースをまとめています。最初から全章を読む必要はありません。</p><p>「この条件では使えない」「この手順は曖昧」といった具体的な反証例は、<a href="https://github.com/aidhidesupport/iap/issues">GitHubのIssue</a>へ。個人名・顧客資料・診断情報・資格情報を含まない、架空の小さな例で十分です。</p><p>仕様・ガイドはCC BY 4.0、基本実装はApache-2.0で公開します。商用利用に個別の許可や寄付は不要です。再配布・改変時の表示や対象範囲は、<a href="https://github.com/aidhidesupport/iap/blob/main/RIGHTS.md">利用条件</a>を確認してください。</p><div className="guide-next"><TextLink href="/guide/developer">開発者向けの実装ガイド</TextLink><TextLink href="/status">実装と検証の現在地</TextLink></div></Section>
</Guide>;}
